# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
# avoid duplicate tests in PRs
branches:
  only:
    - master
julia:
  - 1
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("SpiderMonkey")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("SpiderMonkey")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
